# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerGroupFilter
                                 A QGIS plugin
 Manage your Layer Filters (data subset) using layer-groups
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-16
        copyright            : (C) 2018 by Peter Bontinck
        email                : bontinck.p@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerGroupFilter class from file LayerGroupFilter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    print("Starting plugin initialization in classFactory...")
    try:
        from .layer_group_filter import LayerGroupFilter
        print("LayerGroupFilter class imported successfully")
        plugin = LayerGroupFilter(iface)
        print("LayerGroupFilter instance created successfully")
        return plugin
    except Exception as e:
        print(f"Error during plugin initialization: {str(e)}")
        raise

def name():
    return "Smart Layer Filter"

def description():
    return "Manage your Layer Filters (data subset) using layer-groups"

def version():
    return "0.0.1"

def qgisMinimumVersion():
    return "3.0"

def author():
    return "Peter Bontinck"

def email():
    return "bontinck.p@gmail.com"

def icon():
    return "icon.png"

def category():
    return "Plugins"

def tags():
    return "filter,layer,group"
