# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerGroupFilterDockWidget
                                 A QGIS plugin
 Manage your Layer Filters (data subset) using layer-groups
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-16
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Peter Bontinck
        email                : bontinck.p@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QDockWidget
from PyQt5.QtCore import pyqtSignal

# Import the code for the DockWidget
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), 'smart_layer_filter_dockwidget_base.ui'))

class SmartLayerFilterDockWidget(QDockWidget, FORM_CLASS):
    """DockWidget implementation."""

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(SmartLayerFilterDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        """Close event."""
        self.closingPlugin.emit()
        event.accept()
