# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Smart Layer Filter
                                 A QGIS plugin
 Manage your Layer Filters (data subset) using layer-groups
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-05-16
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Peter Bontinck
        email                : bontinck.p@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import *
try:
    from qgis.core import QgsFeatureIds
except ImportError:
    QgsFeatureIds = None
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QSettings,
    QTranslator,
    pyqtSignal,
    qVersion,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QApplication,
    QComboBox,
    QCompleter,
    QFileDialog,
    QListWidgetItem,
    QMessageBox,
)
import os.path
import xml.etree.ElementTree as ET

from .resources import *
from .pyqt_compat import (
    QAbstractItemView_SingleSelection,
    QAction,
    QComboBox_NoInsert,
    QCompleter_PopupCompletion,
    Qgis_Critical,
    Qgis_Info,
    Qgis_Warning,
    QgsFeatureRequest_NoGeometry,
    QgsTask_Running,
    QgsWkb_PointGeometry,
    Qt_CaseInsensitive,
    Qt_DisplayRole,
    Qt_LeftDockWidgetArea,
    Qt_MatchContains,
    Qt_UserRole,
    Qt_UserRole1,
    Qt_WaitCursor,
    font_metrics_horizontal_advance,
)

from .layer_group_filter_dockwidget import SmartLayerFilterDockWidget


def _provider_can_scan_unique_values(provider):
    """고유값 수집은 속성 편집(ChangeAttributeValues)과 무관. ZIP/OGR 읽기 전용도 조회 시도."""
    return provider is not None


def _vector_layers_in_group(group):
    """그룹 내 벡터 레이어 목록(트리 순서)."""
    out = []
    if not group:
        return out
    for tree_layer in group.findLayers():
        lyr = tree_layer.layer()
        if isinstance(lyr, QgsVectorLayer) and lyr.dataProvider():
            out.append(lyr)
    return out


def _field_names_for_filter_ui(layer):
    """Filter Attribute / Value label 콤보에 넣을 필드명(시스템 필드 제외)."""
    exclude_fields = {"gid", "fid", "objectid", "id", "oid", "pk", "primary_key"}
    return [
        f.name()
        for f in layer.fields()
        if f.name().lower() not in exclude_fields
    ]


def _field_names_for_locate(layer):
    """속성 찾기 탭: 모든 속성 필드명."""
    return [f.name() for f in layer.fields()]


def _expression_quote_field(name):
    """QgsExpression: 필드명 인용(버전별 API 차이 대응)."""
    qe = QgsExpression
    if hasattr(qe, "quoteFieldIdentifier"):
        return qe.quoteFieldIdentifier(name)
    if hasattr(qe, "quotedColumnRef"):
        return qe.quotedColumnRef(name)
    return '"' + str(name).replace('"', '""') + '"'


def _expression_quote_string_literal(text):
    """QgsExpression: 문자열 리터럴 인용(검색어)."""
    qe = QgsExpression
    if hasattr(qe, "quotedValue"):
        return qe.quotedValue(text)
    if hasattr(qe, "quotedString"):
        return qe.quotedString(str(text))
    return "'" + str(text).replace("'", "''") + "'"


class FilterValueTask(QgsTask):
    """백그라운드에서 필터 값을 가져오는 작업"""
    valuesReady = pyqtSignal(list, str)  # values, layer_id
    
    def __init__(self, layer, fieldIndex, layer_id):
        super().__init__()
        self.layer = layer
        self.fieldIndex = fieldIndex
        self.layer_id = layer_id
        self._is_cancelled = False
        self._is_completed = False
        QgsMessageLog.logMessage(f"FilterValueTask initialized: layer={layer.name()}, fieldIndex={fieldIndex}, layer_id={layer_id}", level=Qgis_Info)
        
    def cancel(self):
        """작업 취소 시 호출되는 메서드"""
        if not self._is_cancelled:
            self._is_cancelled = True
            super().cancel()
            QgsMessageLog.logMessage("Task cancelled", level=Qgis_Info)
        
    def finished(self, result):
        """작업 완료 시 호출되는 메서드"""
        if not self._is_completed:
            self._is_completed = True
            super().finished(result)
            QgsMessageLog.logMessage("Task completed", level=Qgis_Info)
        
    def run(self):
        try:
            if self._is_cancelled:
                return False
                
            QgsMessageLog.logMessage(f"Starting FilterValueTask.run for layer: {self.layer.name()}", level=Qgis_Info)
            # uniqueValues를 사용하여 고유값을 가져옴
            provider = self.layer.dataProvider()
            if _provider_can_scan_unique_values(provider):
                field_name = self.layer.fields().at(self.fieldIndex).name()
                QgsMessageLog.logMessage(f"Getting unique values for field: {field_name}", level=Qgis_Info)
                
                # 현재 필터 문자열 저장
                current_filter = self.layer.subsetString()
                
                # 필터 제거
                self.layer.setSubsetString("")
                
                # uniqueValues 메서드를 사용하여 고유값 가져오기
                values = provider.uniqueValues(self.fieldIndex)
                
                # 원래 필터 복원
                self.layer.setSubsetString(current_filter)
                
                if self._is_cancelled:
                    return False
                    
                if values:
                    # None 값 제외하고 문자열로 변환
                    values = [str(v) for v in values if v is not None]
                    QgsMessageLog.logMessage(f"Found {len(values)} unique values", level=Qgis_Info)
                    self.valuesReady.emit(values, self.layer_id)
                    return True
                else:
                    QgsMessageLog.logMessage("No unique values found", level=Qgis_Warning)
            else:
                QgsMessageLog.logMessage("Provider not available or cannot scan unique values", level=Qgis_Warning)
            return False
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in FilterValueTask: {str(e)}", level=Qgis_Critical)
            return False

class valueRelationException(Exception): pass

class LayerGroupFilter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        QgsMessageLog.logMessage("Initializing LayerGroupFilter class...", tag="Smart Layer Filter")
        try:
            # Save reference to the QGIS interface
            self.iface = iface
            QgsMessageLog.logMessage("QGIS interface reference saved", tag="Smart Layer Filter")

            # initialize plugin directory
            self.plugin_dir = os.path.dirname(__file__)
            QgsMessageLog.logMessage(f"Plugin directory: {self.plugin_dir}", tag="Smart Layer Filter")

            # initialize locale
            locale = QSettings().value('locale/userLocale')[0:2]
            locale_path = os.path.join(
                self.plugin_dir,
                'i18n',
                'SmartLayerFilter_{}.qm'.format(locale))

            if os.path.exists(locale_path):
                QgsMessageLog.logMessage(f"Loading translation from: {locale_path}", tag="Smart Layer Filter")
                self.translator = QTranslator()
                self.translator.load(locale_path)

                if qVersion() > '4.3.3':
                    QCoreApplication.installTranslator(self.translator)
                    QgsMessageLog.logMessage("Translator installed successfully", tag="Smart Layer Filter")
            else:
                QgsMessageLog.logMessage(f"No translation file found at: {locale_path}", tag="Smart Layer Filter")

            # Declare instance attributes
            self.actions = []
            self.menu = self.tr(u'&Smart Layer Filter')
            self.toolbar = self.iface.addToolBar(u'SmartLayerFilter')
            self.toolbar.setObjectName(u'SmartLayerFilter')
            QgsMessageLog.logMessage("Toolbar and menu initialized", tag="Smart Layer Filter")

            self.pluginIsActive = False
            self.dockwidget = None
            # 속성 찾기: 마지막 검색이 수행된 레이어 ID(다른 레이어로 바뀌면 목록 초기화)
            self._locate_results_layer_id = None

            # 캐시 초기화
            self.filter_value_cache = {}
            self.field_index_cache = {}
            self.BATCH_SIZE = 100
            # 레이어 그룹별 독 위젯 상태 (그룹 전환 시 복원)
            self.group_ui_state = {}
            self._active_layer_group_index = None
            QgsMessageLog.logMessage("Caches initialized", tag="Smart Layer Filter")
            
            # 필터 프리셋 초기화
            self.filterPresets = []
            self.filterXmlRoot = None
            self.allGroups = []
            self.root = None
            QgsMessageLog.logMessage("Filter presets initialized", tag="Smart Layer Filter")
            
            # 작업자 스레드 관리
            self.workers = []
            self._current_values = set()
            self._is_loading = False
            QgsMessageLog.logMessage("Worker threads initialized", tag="Smart Layer Filter")

            self.task_manager = QgsApplication.taskManager()
            self.tasks = []
            self._filter_value_completer = None
            QgsMessageLog.logMessage("Task manager initialized", tag="Smart Layer Filter")

            QgsMessageLog.logMessage("LayerGroupFilter initialization completed successfully", tag="Smart Layer Filter")
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during LayerGroupFilter initialization: {str(e)}", tag="Smart Layer Filter")
            raise

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LayerGroupFilter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        try:
            icon_path = ':/plugins/smart_layer_filter/icon.png'
            self.add_action(
                icon_path,
                text=self.tr(u'Smart Layer Filter'),
                callback=self.run,
                parent=self.iface.mainWindow())
            self.add_action(
                icon_path,
                text=self.tr('필터 프리셋 XML 불러오기…'),
                callback=self.loadXml,
                parent=self.iface.mainWindow(),
                add_to_toolbar=False,
            )

            QgsMessageLog.logMessage("GUI initialization completed", tag="Smart Layer Filter")
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in initGui: {str(e)}", tag="Smart Layer Filter")

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING LayerGroupFilter"

        try:
            # 작업자 스레드 정리
            for task in self.tasks:
                if task.status() == QgsTask_Running:
                    task.cancel()
            self.tasks.clear()
            
            # disconnects
            self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
            
            self.pluginIsActive = False
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in onClosePlugin: {str(e)}", tag="Smart Layer Filter")

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD LayerGroupFilter"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Smart Layer Filter'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        try:
            self.iface.currentLayerChanged.disconnect(self._on_locate_active_layer_changed)
        except TypeError:
            pass

    #--------------------------------------------------------------------------

    def _on_filter_value_text_edited(self, text):
        """타이핑 즉시 자동완성 팝업 갱신(QComboBox 기본 동작은 접두사 갱신이 늦는 경우가 있음)."""
        c = self._filter_value_completer
        if not c:
            return
        c.setCompletionPrefix(text)
        if text:
            c.complete()
        else:
            c.popup().hide()

    LOCATE_MAX_RESULTS = 500
    LOCATE_TAB_INDEX = 1

    def _setup_locate_tab(self):
        d = self.dockwidget
        lw = d.locateResultsListWidget
        lw.setSelectionMode(QAbstractItemView_SingleSelection)
        lw.itemClicked.connect(self._on_locate_item_clicked)
        d.locateSearchPushButton.clicked.connect(self._locate_run_search)
        d.locateSearchLineEdit.returnPressed.connect(self._locate_run_search)
        d.locatePanPushButton.clicked.connect(self._locate_pan_to_selected)
        d.locateZoomPushButton.clicked.connect(self._locate_zoom_to_selected)
        lw.itemDoubleClicked.connect(self._on_locate_result_double_clicked)
        d.mainTabWidget.currentChanged.connect(self._on_main_tab_changed)
        self.iface.currentLayerChanged.connect(self._on_locate_active_layer_changed)
        self._update_locate_tab_layer_info()

    def _on_main_tab_changed(self, index):
        if index == self.LOCATE_TAB_INDEX:
            self._update_locate_tab_layer_info()

    def _on_locate_active_layer_changed(self, layer):
        if not self.dockwidget:
            return
        if self.dockwidget.mainTabWidget.currentIndex() != self.LOCATE_TAB_INDEX:
            return
        self._update_locate_tab_layer_info()

    def _locate_clear_results_if_layer_mismatch(self, cur_layer_id):
        """검색 결과가 있던 레이어와 활성 레이어가 다르면 목록·상태 초기화."""
        prev = getattr(self, "_locate_results_layer_id", None)
        if prev is None or prev == cur_layer_id:
            return
        d = self.dockwidget
        if not d:
            return
        d.locateResultsListWidget.clear()
        d.locateStatusLabel.setText("")
        self._locate_results_layer_id = None

    def _update_locate_tab_layer_info(self):
        d = self.dockwidget
        layer = self.iface.activeLayer()
        cur_id = layer.id() if isinstance(layer, QgsVectorLayer) and layer.dataProvider() else None
        self._locate_clear_results_if_layer_mismatch(cur_id)
        if not isinstance(layer, QgsVectorLayer) or not layer.dataProvider():
            d.locateLayerInfoLabel.setText(
                self.tr("레이어 패널에서 벡터 레이어를 선택하세요.")
            )
            d.locateFieldComboBox.blockSignals(True)
            d.locateFieldComboBox.clear()
            d.locateFieldComboBox.blockSignals(False)
            d.locateFieldComboBox.setEnabled(False)
            d.locateSearchLineEdit.setEnabled(False)
            d.locateSearchPushButton.setEnabled(False)
            d.locatePanPushButton.setEnabled(False)
            d.locateZoomPushButton.setEnabled(False)
            d.locateStatusLabel.setText("")
            return
        d.locateLayerInfoLabel.setText(
            self.tr("대상 레이어: {0}").format(layer.name())
        )
        d.locateFieldComboBox.blockSignals(True)
        d.locateFieldComboBox.clear()
        d.locateFieldComboBox.addItems(_field_names_for_locate(layer))
        d.locateFieldComboBox.blockSignals(False)
        d.locateFieldComboBox.setEnabled(True)
        d.locateSearchLineEdit.setEnabled(True)
        d.locateSearchPushButton.setEnabled(True)
        d.locatePanPushButton.setEnabled(True)
        d.locateZoomPushButton.setEnabled(True)
        if d.locateFieldComboBox.count() > 0:
            d.locateFieldComboBox.setCurrentIndex(0)

    def _locate_expression(self, field_name, search_text):
        qf = _expression_quote_field(field_name)
        qv = _expression_quote_string_literal(search_text)
        return QgsExpression(f"strpos(lower(to_string({qf})), lower({qv})) > 0")

    def _locate_field_display_label(self, layer, field_index):
        f = layer.fields().at(field_index)
        if hasattr(f, "displayName"):
            dn = f.displayName()
            if dn:
                return dn
        al = f.alias()
        if al:
            return al
        return f.name()

    def _locate_format_result_row(self, layer, feat, field_index):
        label = self._locate_field_display_label(layer, field_index)
        try:
            raw = feat.attribute(field_index)
            s = "" if raw is None else str(raw)
        except Exception:
            s = ""
        if not s:
            s = self.tr("(값 없음)")
        if len(s) > 100:
            s = s[:97] + "..."
        return self.tr("{0}: {1}").format(label, s)

    def _locate_result_tooltip(self, layer, feat, search_field_index):
        lines = []
        n = layer.fields().size()
        for i in range(n):
            if i == search_field_index:
                continue
            fld = layer.fields().at(i)
            lab = fld.displayName() if hasattr(fld, "displayName") else fld.name()
            try:
                v = feat.attribute(i)
            except Exception:
                continue
            if v is None:
                continue
            sv = str(v).strip()
            if not sv:
                continue
            if len(sv) > 70:
                sv = sv[:67] + "..."
            lines.append(f"{lab}: {sv}")
            if len(lines) >= 10:
                break
        return "\n".join(lines)

    def _on_locate_item_clicked(self, item):
        self.dockwidget.locateResultsListWidget.setCurrentItem(item)

    def _locate_run_search(self):
        layer = self.iface.activeLayer()
        d = self.dockwidget
        if not isinstance(layer, QgsVectorLayer) or not layer.dataProvider():
            QMessageBox.information(
                d,
                self.tr("속성 찾기"),
                self.tr("레이어 패널에서 벡터 레이어를 선택하세요."),
            )
            return
        field_name = d.locateFieldComboBox.currentText()
        if not field_name:
            QMessageBox.information(
                d,
                self.tr("속성 찾기"),
                self.tr("검색할 속성을 선택하세요."),
            )
            return
        search_text = d.locateSearchLineEdit.text().strip()
        if not search_text:
            QMessageBox.information(
                d,
                self.tr("속성 찾기"),
                self.tr("검색어를 입력하세요."),
            )
            return
        exp = self._locate_expression(field_name, search_text)
        if exp.hasParserError():
            QMessageBox.warning(
                d,
                self.tr("속성 찾기"),
                self.tr("식 오류: {0}").format(exp.parserErrorString()),
            )
            return
        req = QgsFeatureRequest(exp).setLimit(self.LOCATE_MAX_RESULTS + 1)
        fidx = layer.fields().lookupField(field_name)
        if fidx < 0:
            QMessageBox.warning(d, self.tr("속성 찾기"), self.tr("필드를 찾을 수 없습니다."))
            return
        lw = d.locateResultsListWidget
        lw.clear()
        d.locateStatusLabel.setText(self.tr("검색 중…"))
        QApplication.processEvents()
        QApplication.setOverrideCursor(Qt_WaitCursor)
        feats = []
        try:
            feats = list(layer.getFeatures(req))
        finally:
            QApplication.restoreOverrideCursor()
            QApplication.processEvents()
        truncated = len(feats) > self.LOCATE_MAX_RESULTS
        feats = feats[: self.LOCATE_MAX_RESULTS]
        lid = layer.id()
        for feat in feats:
            row = self._locate_format_result_row(layer, feat, fidx)
            it = QListWidgetItem(row)
            it.setData(Qt_UserRole, feat.id())
            it.setData(Qt_UserRole1, lid)
            tip = self._locate_result_tooltip(layer, feat, fidx)
            if tip:
                it.setToolTip(tip)
            lw.addItem(it)
        if not feats:
            d.locateStatusLabel.setText(self.tr("일치 없음"))
            QMessageBox.information(
                d,
                self.tr("속성 찾기"),
                self.tr("일치하는 피처가 없습니다."),
            )
        else:
            msg = self.tr("{0}건 — 목록에서 줄을 클릭해 선택한 뒤 이동·확대하세요.").format(
                len(feats)
            )
            d.locateStatusLabel.setText(msg)
            if truncated:
                d.locateStatusLabel.setText(
                    msg
                    + " "
                    + self.tr("(상한 {0}건까지만 표시)").format(self.LOCATE_MAX_RESULTS)
                )
                QgsMessageLog.logMessage(
                    self.tr("일치 피처가 많아 최대 {0}건만 목록에 표시했습니다.").format(
                        self.LOCATE_MAX_RESULTS
                    ),
                    tag="Smart Layer Filter",
                    level=Qgis_Info,
                )
            if lw.count() > 0:
                lw.setCurrentRow(0)
        self._locate_results_layer_id = layer.id()

    def _locate_resolve_selection(self):
        item = self.dockwidget.locateResultsListWidget.currentItem()
        if item is None:
            return None, None, None
        fid = item.data(Qt_UserRole)
        lid = item.data(Qt_UserRole1)
        if lid is None or fid is None:
            return None, None, None
        lyr = QgsProject.instance().mapLayer(lid)
        if not isinstance(lyr, QgsVectorLayer):
            return None, None, None
        feat = lyr.getFeature(fid)
        if not feat.isValid():
            return None, None, None
        return lyr, feat, item

    def _locate_geometry_for_canvas(self, layer, geom):
        """레이어에 저장된 CRS의 지오메트리를 지도(캔버스 destinationCrs)로 변환."""
        if geom is None or geom.isNull():
            return None
        canvas = self.iface.mapCanvas()
        dest = canvas.mapSettings().destinationCrs()
        src = layer.crs()
        g = QgsGeometry(geom)
        if not src.isValid() or not dest.isValid():
            return g
        if src.authid() == dest.authid() or src == dest:
            return g
        xform = QgsCoordinateTransform(src, dest, QgsProject.instance())
        try:
            xform.setBallparkTransformsAreAppropriate(True)
        except Exception:
            pass
        try:
            g.transform(xform)
        except Exception as e:
            QgsMessageLog.logMessage(
                self.tr("좌표 변환 실패: {0}").format(str(e)),
                tag="Smart Layer Filter",
                level=Qgis_Warning,
            )
            return None
        if g.isNull():
            return None
        return g

    def _locate_focal_point_xy(self, geom):
        """이동·중심 계산용: 점은 좌표, 면·선은 centroid, 실패 시 bbox 중심."""
        if geom is None or geom.isNull():
            return None
        try:
            if geom.type() == QgsWkb_PointGeometry:
                if geom.isMultipart():
                    mp = geom.asMultiPoint()
                    if mp:
                        p = mp[0]
                        return QgsPointXY(p)
                return QgsPointXY(geom.asPoint())
            cen = geom.centroid()
            if cen is not None and not cen.isNull():
                return QgsPointXY(cen.asPoint())
        except Exception:
            pass
        return geom.boundingBox().center()

    def _locate_extent_for_zoom(self, canvas, geom):
        """확대용 범위: 여유 마진을 두어 화면에서 잘 보이게."""
        if geom is None or geom.isNull():
            return None
        try:
            mupp = canvas.mapSettings().mapUnitsPerPixel()
        except Exception:
            mupp = 1.0
        rect = geom.boundingBox()
        if rect.width() < 1e-12 and rect.height() < 1e-12:
            c = rect.center()
            d = max(mupp * 45.0, 1.0)
            return QgsRectangle(c.x() - d, c.y() - d, c.x() + d, c.y() + d)
        cx = rect.center().x()
        cy = rect.center().y()
        half_w = rect.width() / 2.0
        half_h = rect.height() / 2.0
        margin_x = max(half_w * 0.45, mupp * 18.0)
        margin_y = max(half_h * 0.45, mupp * 18.0)
        return QgsRectangle(
            cx - half_w - margin_x,
            cy - half_h - margin_y,
            cx + half_w + margin_x,
            cy + half_h + margin_y,
        )

    def _locate_map_feedback(self, layer, feat):
        """선택 피처를 지도에서 잠시 강조."""
        canvas = self.iface.mapCanvas()
        geom = feat.geometry()
        dest = canvas.mapSettings().destinationCrs()
        g_map = self._locate_geometry_for_canvas(layer, geom) if geom and not geom.isNull() else None
        try:
            if QgsFeatureIds is not None and hasattr(canvas, "flashFeatureIds"):
                fids = QgsFeatureIds()
                fids.add(feat.id())
                canvas.flashFeatureIds(layer, fids)
                return
        except Exception:
            pass
        try:
            if g_map is not None and not g_map.isNull() and hasattr(canvas, "flashGeometries"):
                canvas.flashGeometries([g_map], dest)
        except Exception:
            pass

    def _locate_pan_to_selected(self):
        lyr, feat, _ = self._locate_resolve_selection()
        if lyr is None:
            QMessageBox.information(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("목록에서 피처를 선택하세요."),
            )
            return
        geom = feat.geometry()
        if geom is None or geom.isNull():
            QMessageBox.information(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("이 피처에는 이동할 수 있는 지오메트리가 없습니다."),
            )
            return
        g_map = self._locate_geometry_for_canvas(lyr, geom)
        if g_map is None:
            QMessageBox.warning(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("레이어 좌표를 지도 좌표로 바꾸지 못했습니다. 프로젝트 CRS와 레이어 CRS를 확인하세요."),
            )
            return
        c = self._locate_focal_point_xy(g_map)
        if c is None:
            return
        canvas = self.iface.mapCanvas()
        rect = canvas.extent()
        half_w = rect.width() / 2.0
        half_h = rect.height() / 2.0
        new_rect = QgsRectangle(
            c.x() - half_w, c.y() - half_h, c.x() + half_w, c.y() + half_h
        )
        canvas.setExtent(new_rect)
        canvas.refresh()
        self._locate_map_feedback(lyr, feat)

    def _locate_zoom_to_selected(self):
        lyr, feat, _ = self._locate_resolve_selection()
        if lyr is None:
            QMessageBox.information(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("목록에서 피처를 선택하세요."),
            )
            return
        geom = feat.geometry()
        if geom is None or geom.isNull():
            QMessageBox.information(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("이 피처에는 확대할 수 있는 지오메트리가 없습니다."),
            )
            return
        g_map = self._locate_geometry_for_canvas(lyr, geom)
        if g_map is None:
            QMessageBox.warning(
                self.dockwidget,
                self.tr("속성 찾기"),
                self.tr("레이어 좌표를 지도 좌표로 바꾸지 못했습니다. 프로젝트 CRS와 레이어 CRS를 확인하세요."),
            )
            return
        canvas = self.iface.mapCanvas()
        rect = self._locate_extent_for_zoom(canvas, g_map)
        if rect is None:
            return
        canvas.setExtent(rect)
        canvas.refresh()
        self._locate_map_feedback(lyr, feat)

    def _on_locate_result_double_clicked(self, item):
        self.dockwidget.locateResultsListWidget.setCurrentItem(item)
        self._locate_zoom_to_selected()

    def run(self):
        """Run method that loads and starts the plugin"""
        QgsMessageLog.logMessage("Starting plugin initialization...", tag="Smart Layer Filter")
        if not self.pluginIsActive:
            self.pluginIsActive = True

            QgsMessageLog.logMessage("** STARTING LayerGroupFilter", tag="Smart Layer Filter")

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                QgsMessageLog.logMessage("Creating new dockwidget...", tag="Smart Layer Filter")
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = SmartLayerFilterDockWidget()
                
                # 필터 연산자 콤보박스 초기화
                QgsMessageLog.logMessage("Initializing filter operator combo box...", tag="Smart Layer Filter")
                self._setup_filter_operator_combo()
                
                # 필터 값: 편집 + 자동완성(콤보 모델과 동일 소스 — 고유값 로드 후 팝업에 반영됨)
                QgsMessageLog.logMessage("Setting up filter value combo box autocompletion...", tag="Smart Layer Filter")
                fv = self.dockwidget.filterValueComboBox
                fv.setEditable(True)
                fv.setInsertPolicy(QComboBox_NoInsert)
                completer = QCompleter(fv.model(), fv)
                completer.setCaseSensitivity(Qt_CaseInsensitive)
                completer.setFilterMode(Qt_MatchContains)
                completer.setCompletionMode(QCompleter_PopupCompletion)
                completer.setCompletionRole(Qt_DisplayRole)
                completer.setMaxVisibleItems(20)
                completer.setWrapAround(False)
                fv.setCompleter(completer)
                self._filter_value_completer = completer
                le = fv.lineEdit()
                if le is not None:
                    le.textEdited.connect(self._on_filter_value_text_edited)
                fv.setToolTip(
                    self.tr(
                        "글자를 칠 때마다 일치하는 값이 팝업으로 뜹니다(대소문자 무시, 일부만 입력해도 검색). "
                        "▼ 목록·제안에서 선택하거나 직접 입력할 수 있습니다."
                    )
                )
                QgsMessageLog.logMessage("Filter value combo box autocompletion setup completed", tag="Smart Layer Filter")
                
                # 버튼 연결
                QgsMessageLog.logMessage("Connecting button signals...", tag="Smart Layer Filter")
                self.dockwidget.replacePushButton.clicked.connect(self.replaceFilters)
                self.dockwidget.addPushButton.clicked.connect(self.addFilter)
                self.dockwidget.clearPushButton.clicked.connect(self.clearFilters)
                self.dockwidget.loadValuesButton.clicked.connect(lambda: self.updateDistinctValues(manual=True))
                QgsMessageLog.logMessage("Button signals connected", tag="Smart Layer Filter")

                # 콤보박스 연결
                QgsMessageLog.logMessage("Connecting combo box signals...", tag="Smart Layer Filter")
                self.dockwidget.layerGroupComboBox.currentIndexChanged.connect(self.layerGroupChanged)
                self.dockwidget.layerInGroupComboBox.currentIndexChanged.connect(self.onLayerInGroupChanged)
                self.dockwidget.filterAttributeComboBox.currentIndexChanged.connect(self.onFilterAttributeChanged)
                self.dockwidget.valueLabelColumnComboBox.currentIndexChanged.connect(
                    self.onValueLabelColumnChanged
                )
                QgsMessageLog.logMessage("Combo box signals connected", tag="Smart Layer Filter")

                self._setup_locate_tab()
                QgsMessageLog.logMessage("Locate tab initialized", tag="Smart Layer Filter")

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            QgsMessageLog.logMessage("Adding dockwidget to QGIS interface...", tag="Smart Layer Filter")
            self.iface.addDockWidget(Qt_LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            
            QgsMessageLog.logMessage("Reloading project...", tag="Smart Layer Filter")
            self.reloadProject()
            QgsMessageLog.logMessage("Plugin initialization completed", tag="Smart Layer Filter")
        else:
            QgsMessageLog.logMessage("Plugin is already active", tag="Smart Layer Filter")

    def reloadProject(self):
        """(re)intitiation of the Plugin."""
        QgsMessageLog.logMessage("Starting project reload...", tag="Smart Layer Filter")
        self.group_ui_state.clear()
        self._active_layer_group_index = None
        
        # save the layerTreeRoot
        self.root = QgsProject.instance().layerTreeRoot() 
        QgsMessageLog.logMessage("Layer tree root saved", tag="Smart Layer Filter")
        
        #create emty list for alle LayerGroupes and there Layers to be saved in.
        #And fill with current LayerGroupes and corresponding Layers
        self.allGroups = [] 
        self.discoverGroups() 
        QgsMessageLog.logMessage(f"Found {len(self.allGroups)} layer groups", tag="Smart Layer Filter")
        
        #initate layerGroupComboBox 
        self.dockwidget.layerGroupComboBox.clear()
        self.dockwidget.layerGroupComboBox.addItems(i[0] for i in self.allGroups)
        QgsMessageLog.logMessage("Layer group combo box updated", tag="Smart Layer Filter")
        
        #check if the current QGIS project has a "groupFilterPresets" XML as project variable
        if QgsExpressionContextUtils.projectScope(QgsProject.instance()).variable("groupFilterPresets"):
            QgsMessageLog.logMessage("Loading filter presets from project...", tag="Smart Layer Filter")
            #pharse the XML string  to XML object and further initialize the plugin.
            self.filterXmlRoot = ET.fromstring(QgsExpressionContextUtils.projectScope(QgsProject.instance()).variable("groupFilterPresets"))
            self.loadFilterPresets()
        else:
            QgsMessageLog.logMessage("No filter presets found in project", tag="Smart Layer Filter")
            # 필터 프리셋이 없는 경우 빈 리스트로 초기화
            self.filterPresets = []
            QgsMessageLog.logMessage(
                "프로젝트 변수 groupFilterPresets 없음(선택). 메뉴에서 XML을 불러올 수 있습니다.",
                tag="Smart Layer Filter",
                level=Qgis_Info,
            )
        
        QgsMessageLog.logMessage("Project reload completed", tag="Smart Layer Filter")
	
    def discoverGroups(self):
        """save all layer Tree Groups of the project in a 2D list, self.allGroups :
        [[layerGroup name,[list of ALL layersID's in the group], QgsLayerTreeGroup], ...]
            remark: for sub-groups we add a prefix to the  saved layerGroup name;
            세 번째 요소는 findGroup(표시용 이름)이 실패하지 않도록 실제 트리 그룹 노드 참조
        """ 
        
        self.allGroups=[] 
        self.discoverBranch (self.root.children(), "")
		
    def discoverBranch(self, parrent, groupNamePrefix ):
        """discover recursively a list of Nodes , a Group or a layer) to the bottoms and append all LayerTreeGroups to self.allGroups with all their layerID's"""
        
        if isinstance(parrent, QgsLayerTreeGroup):
            
            # append the found group (표시용 고유 키, 레이어 id 목록, 트리 노드)
            self.allGroups.append([
                groupNamePrefix + parrent.name(),
                [treeLayer.layerId() for treeLayer in parrent.findLayers()],
                parrent,
            ])
            
            # go look for sub_groups
            #to the name of sub groups we add a prefix, to distict them in the GUI          
            newGroupNamePrefix = groupNamePrefix + "__ "
            self.discoverBranch (parrent.children(),newGroupNamePrefix )

        elif isinstance(parrent, QgsLayerTreeLayer):
            
            #layers do not need further inverigation , there are al ready saved by ID with there parrents (and grand parrents)
            pass
        
        else : #parrent is list of nodes as reslut of layerTreeNode.children()
            
           for child in parrent:
                  self.discoverBranch (child,groupNamePrefix)

    def loadFilterPresets(self):
        """프로젝트 XML의 preset 목록(고급 API·changeSubsetStrings용). 도크에는 표시하지 않음."""
        self.filterPresets = [[preset.get('name'), preset] for preset in self.filterXmlRoot.findall('preset')]
    
    def GetValueRelation(self, presetXml):
        """check if a Filter Preset XML object has a Value relation
        if:  no value Relation -> rerurn = None
        else: return Value Relation XML object """
        vr = presetXml.findall("valueRelation")
        if len(vr) > 0:  # 명시적으로 길이 체크
            return vr[0]  # only return first ValueRelation, others will be ignored
        else:
            return None
        
        
    
    def changeSubsetStrings(self, presetIndex=None, groupIndex=None, values=None, clearAll=False):
        """최적화된 필터 문자열 변경 메서드"""
        if groupIndex is None:
            groupIndex = self.dockwidget.layerGroupComboBox.currentIndex()
        if groupIndex < 0:
            return
            
        group = self.getLayerGroup(groupIndex)
        if not group:
            return
            
        # 배치 처리 시작
        layer_updates = []
        
        for layer in group.findLayers():
            vl = layer.layer()
            if not isinstance(vl, QgsVectorLayer) or not vl.dataProvider():
                continue
            fieldIndex = self.getFilterFieldIndex(vl)
            if fieldIndex >= 0:
                if clearAll:
                    vl.setSubsetString("")
                else:
                    subsetString = self.createSubsetString(
                        vl,
                        fieldIndex,
                        values,
                        presetIndex
                    )
                    layer_updates.append((vl, subsetString))
        
        # 배치로 업데이트 실행
        for i in range(0, len(layer_updates), self.BATCH_SIZE):
            batch = layer_updates[i:i + self.BATCH_SIZE]
            for layer, subsetString in batch:
                layer.setSubsetString(subsetString)
                
        # 지도 캔버스 갱신
        self.iface.mapCanvas().refresh()
        # 레이어 패널 갱신
        for layer in group.findLayers():
            self.iface.layerTreeView().refreshLayerSymbology(layer.layerId())

    def getValueRelation(self, value, valueRelationXml, invert = False, getAll = False):
        """
        returns the value(s) found in the value column , corresponding to a Key column of a other layer/table
            - value : value to look for in the key column
            - valueRelationXml : Layer, Key column, value column are given as a XMLobject 
            - invert : if True, the inveted value relation is returned
            - getAll: if False, only first value is returned, if false a LIST of all values is returned
        """
        
        #initialize warnings
        warning = False
        warningText = ""
        
        #parse valueRelationXml in dictionary
        vr ={"Layer":"", "keyColumn":"", "valueColumn":""}
        vr["Layer"] =valueRelationXml.find("Layer").text
        vr["keyColumn"] =  valueRelationXml.find("keyColumn").text
        vr["valueColumn"] =  valueRelationXml.find("valueColumn").text
        
        #inverting valueRelation if necessary
        if invert :
            temp = vr["keyColumn"]
            vr["keyColumn"] = vr["valueColumn"]
            vr["valueColumn"] = temp
		
		#save the lookup layer in list with len() = 1
        layers = QgsProject.instance().mapLayersByName(vr["Layer"])
      
        #create and save the expression to look up the key value
        exp = '"{0}" = \'{1}\''.format(vr["keyColumn"], value )
        exp = exp.replace("\\", "\\\\") #work around in case a \ appears in value string

        try:
            if len(layers) > 1: #set warning: layername not unique
                warning = True
                warningText= warningText + "layer : {0} is not unique, only first instance is used \n".format( vr["Layer"])
                
        
            if len(layers) < 1: #set warning: layername not found, result will be None
                warning = True
                warningText = warningText + "layer : {0} is not found \n".format( vr["Layer"]) 
                
                raise valueRelationException
        
            #look up the corresponding values
            subset = layers[0].getFeatures( QgsFeatureRequest().setFilterExpression (exp ))

            resultCounter = 0
            
            if getAll:
                result = []
            
            for feature in subset:
                value = feature.attribute(vr["valueColumn"])
                
                if getAll:
                    result.append(value)
                    resultCounter = resultCounter +1
                else:
                
                    if resultCounter > 1: #set warning: to many results
                        warning = True
                        warningText= warningText + "More than one, matiching value found for : {0} , only first is used \n".format( exp)
                    
                        return #GOTO finally , loving this spaghetti :)
                                           
                    result = value
                    resultCounter = resultCounter +1
    
            if resultCounter  == 0:
                warning = True
                warningText = warningText + "No matiching value found for : {0} \n".format( exp)
                
                raise valueRelationException
            
            result = subset[0].attribute(vr["valueColumn"])
            
        except valueRelationException: 
            result = None
        
        finally:
            if warning:
                QgsMessageLog.logMessage(warningText, tag="Smart Layer Filter")  
            return result

    def _clear_filter_value_loading(self):
        """Loading... 등 잘못 남은 플레이스홀더 제거(콤보는 편집 가능이라 빈 상태로 직접 입력 가능)."""
        self.dockwidget.filterValueComboBox.clear()

    def _setup_filter_operator_combo(self):
        """연산자 열 정렬 + 설명(탭 대신 공백 정렬 — 드롭다운에서 탭은 너비에 반영되지 않아 잘림)."""
        cb = self.dockwidget.filterOperatorComboBox
        cb.clear()
        specs = [
            ("=", "값이 정확하게 일치하는항목"),
            ("!=", "값이 일치하지 않는 항목"),
            ("<", "값이 지정된 값보다 작은항목"),
            (">", "값이 지정된 값보다 큰항목"),
            ("<=", "값이 지정된 값보다 작거나같은항목"),
            (">=", "값이 지정된 값보다 크거나같은항목"),
            ("LIKE", "지정된 패턴과 일치하는 항목"),
            ("ILIKE", "대소문자 구분 없이 패턴 일치"),
        ]
        col_w = max(len(s[0]) for s in specs)
        labels = []
        for sym, desc in specs:
            label = f"{sym.ljust(col_w)}  {desc}"
            labels.append((label, sym))
        fm = cb.fontMetrics()
        max_px = 0
        for label, sym in labels:
            cb.addItem(label, sym)
            max_px = max(max_px, font_metrics_horizontal_advance(fm, label))
        cb.setCurrentIndex(0)
        # 드롭다운이 도크보다 과하게 넓어지지 않게 상한. 긴 줄은 목록에서 가로 스크롤로 볼 수 있음
        pad = 16
        max_popup_w = 280
        w = min(max_px + pad, max_popup_w)
        cb.view().setMinimumWidth(max(w, 220))

    def _current_filter_operator_symbol(self):
        """필터 SQL에 쓸 연산자 기호."""
        cb = self.dockwidget.filterOperatorComboBox
        data = cb.currentData()
        if data:
            return data
        t = cb.currentText()
        if not t:
            return "="
        if "\t" in t:
            return t.split("\t", 1)[0].strip()
        parts = t.split(None, 1)
        return parts[0].strip() if parts else "="

    def _set_filter_operator_by_symbol(self, symbol):
        """저장된 연산자 기호로 콤보 선택."""
        cb = self.dockwidget.filterOperatorComboBox
        if not symbol:
            symbol = "="
        idx = cb.findData(symbol, Qt_UserRole)
        if idx >= 0:
            cb.setCurrentIndex(idx)
        else:
            idx = cb.findData("=", Qt_UserRole)
            if idx >= 0:
                cb.setCurrentIndex(idx)

    def _current_reference_vector_layer(self):
        """하위 레이어 콤보에서 선택된 벡터 레이어(필드·고유값 기준)."""
        lid = self.dockwidget.layerInGroupComboBox.currentData()
        if not lid:
            return None
        lyr = QgsProject.instance().mapLayer(lid)
        if isinstance(lyr, QgsVectorLayer) and lyr.dataProvider():
            return lyr
        return None

    def _populate_layer_in_group_combo(self, group, preferred_layer_id=None):
        """그룹 내 벡터 레이어 콤보 채움. preferred_layer_id 있으면 해당 항목 선택."""
        cb = self.dockwidget.layerInGroupComboBox
        cb.blockSignals(True)
        cb.clear()
        layers = _vector_layers_in_group(group)
        for vl in layers:
            cb.addItem(vl.name(), vl.id())
        sel = 0
        if preferred_layer_id and layers:
            for i in range(cb.count()):
                if cb.itemData(i) == preferred_layer_id:
                    sel = i
                    break
        if cb.count() > 0:
            cb.setCurrentIndex(sel)
        cb.blockSignals(False)
        if not layers:
            return None
        return self._current_reference_vector_layer()

    def _iter_filter_target_vector_layers(self):
        """교체/추가/지우기 대상 벡터 레이어: (QgsVectorLayer, symbology 갱신용 layerId)."""
        group_index = self.dockwidget.layerGroupComboBox.currentIndex()
        if group_index < 0:
            return
        group = self.getLayerGroup(group_index)
        if not group:
            return
        if self.dockwidget.applyGroupFilterCheckBox.isChecked():
            for tl in group.findLayers():
                vl = tl.layer()
                if isinstance(vl, QgsVectorLayer) and vl.dataProvider():
                    yield vl, tl.layerId()
        else:
            vl = self._current_reference_vector_layer()
            if vl:
                yield vl, vl.id()

    def _current_value_label_field_name(self):
        """표시용 설명 컬럼명. 없으면 빈 문자열."""
        cb = self.dockwidget.valueLabelColumnComboBox
        if cb.count() <= 0:
            return ""
        data = cb.currentData()
        if data is not None and str(data).strip() != "":
            return str(data)
        return ""

    def _filter_value_cache_key(self, group_index, layer, code_field):
        gname = self.allGroups[group_index][0]
        lbl = self._current_value_label_field_name()
        if lbl:
            return f"{gname}_{layer.id()}_{code_field}__lbl_{lbl}"
        return f"{gname}_{layer.id()}_{code_field}"

    def _format_filter_value_display(self, label_text, code_str):
        """목록·자동완성에 보이는 한 줄(필터 값은 code_str)."""
        code_str = str(code_str)
        if label_text is None:
            label_text = ""
        else:
            label_text = str(label_text).strip()
        if not label_text or label_text == code_str:
            return code_str
        return f"{label_text}  [{code_str}]"

    def _cached_entries_to_pairs(self, cached):
        """캐시 항목: 구버전 list[str] 또는 [(code, display), ...]."""
        if not cached:
            return []
        first = cached[0]
        if isinstance(first, (list, tuple)) and len(first) >= 2:
            return [(str(a), str(b)) for a, b in cached]
        return [(str(x), str(x)) for x in cached]

    def _populate_filter_value_combo_entries(self, entries):
        """entries: (code, display) 정렬된 목록. UserRole=코드."""
        fv = self.dockwidget.filterValueComboBox
        fv.clear()
        for code, disp in entries:
            fv.addItem(disp, code)
        if fv.count() > 0:
            fv.setCurrentIndex(0)

    def _collect_code_to_label_map(self, layer, code_field, label_field):
        """코드값별 첫 번째 설명(라벨) 매핑. getFeatures가 비어도 uniqueValues와 합치면 목록은 유지."""
        code_idx = layer.fields().indexOf(code_field)
        label_idx = layer.fields().indexOf(label_field)
        if code_idx < 0 or label_idx < 0:
            return {}
        pairs = {}
        current_filter = layer.subsetString()
        try:
            layer.setSubsetString("")

            def _scan(use_subset):
                req = QgsFeatureRequest().setFlags(QgsFeatureRequest_NoGeometry)
                if use_subset:
                    # QGIS 3.40+ PyQt6: 필드명(str) 목록이어야 함(int면 "index 0 has type int but str is expected")
                    req.setSubsetOfAttributes([code_field, label_field], layer.fields())
                for f in layer.getFeatures(req):
                    cv = f.attribute(code_idx)
                    if cv is None:
                        continue
                    k = str(cv)
                    if k in pairs:
                        continue
                    lv = f.attribute(label_idx)
                    pairs[k] = str(lv) if lv is not None else k

            _scan(True)
            if not pairs and layer.featureCount() > 0:
                _scan(False)
        finally:
            try:
                layer.setSubsetString(current_filter)
            except Exception:
                pass
        return pairs

    def _unique_code_strings(self, layer, dp, field_index):
        """subset 해제 후 uniqueValues로 코드 문자열 목록(정렬)."""
        current_filter = layer.subsetString()
        try:
            layer.setSubsetString("")
            values = dp.uniqueValues(field_index)
        finally:
            try:
                layer.setSubsetString(current_filter)
            except Exception:
                pass
        str_values = [str(v) for v in values if v is not None]
        return sorted(str_values, key=lambda x: (x.lower(), x))

    def _build_filter_value_entries(self, layer, dp, code_field, field_index, label_field_name):
        """(code, display) 목록. 설명 컬럼이 있어도 코드 목록은 항상 uniqueValues로 확보."""
        codes = self._unique_code_strings(layer, dp, field_index)
        if not label_field_name:
            return [(s, s) for s in codes]

        label_map = self._collect_code_to_label_map(layer, code_field, label_field_name)
        if label_map and len(label_map) < len(codes):
            QgsMessageLog.logMessage(
                f"표시용 컬럼 매핑이 일부 코드에만 있습니다(피처 스캔 {len(label_map)}/{len(codes)}).",
                tag="Smart Layer Filter",
                level=Qgis_Info,
            )
        entries = []
        for code in codes:
            lab = label_map.get(code)
            entries.append((code, self._format_filter_value_display(lab if lab is not None else code, code)))
        return entries

    def _current_filter_value_code(self):
        """subsetString 등에 쓸 실제 코드값(표시 문자열이 아님)."""
        fv = self.dockwidget.filterValueComboBox
        t = fv.currentText()
        if not t or t == "Loading...":
            return ""
        idx = fv.currentIndex()
        if idx >= 0:
            d = fv.itemData(idx)
            if d is not None and str(d) != "":
                return str(d)
        for i in range(fv.count()):
            if fv.itemText(i) == t:
                d = fv.itemData(i)
                if d is not None and str(d) != "":
                    return str(d)
        return t

    def _select_filter_value_by_code(self, code_str):
        if not code_str or code_str == "Loading...":
            return
        fv = self.dockwidget.filterValueComboBox
        for i in range(fv.count()):
            d = fv.itemData(i)
            if d is not None and str(d) == code_str:
                fv.setCurrentIndex(i)
                return
        for i in range(fv.count()):
            if fv.itemText(i) == code_str:
                fv.setCurrentIndex(i)
                return
        fv.setEditText(code_str)

    def _populate_value_label_column_combo(self, layer, preferred_name=""):
        """코드(필터 속성)와 같은 이름은 제외."""
        cb = self.dockwidget.valueLabelColumnComboBox
        none_label = self.tr("(없음)")
        attr = self.dockwidget.filterAttributeComboBox.currentText()
        cb.blockSignals(True)
        cb.clear()
        cb.addItem(none_label, "")
        for name in sorted(_field_names_for_filter_ui(layer), key=str.lower):
            if name == attr:
                continue
            cb.addItem(name, name)
        sel = 0
        if preferred_name:
            ix = cb.findData(preferred_name)
            if ix < 0:
                ix = cb.findText(preferred_name)
            if ix >= 0:
                sel = ix
        cb.setCurrentIndex(sel)
        cb.blockSignals(False)

    def onValueLabelColumnChanged(self, _index):
        """설명 컬럼 변경 시 캐시 키가 달라지므로 강제로 목록 재구성."""
        self.updateDistinctValues(manual=True)

    def updateDistinctValues(self, manual = False):
        """filterValueComboBox에 고유값(표시 문자열 + UserRole 코드) 반영."""
        try:
            QgsMessageLog.logMessage("Starting updateDistinctValues", level=Qgis_Info)

            groupIndex = self.dockwidget.layerGroupComboBox.currentIndex()
            if groupIndex < 0:
                QgsMessageLog.logMessage("Invalid group index", level=Qgis_Warning)
                self._clear_filter_value_loading()
                return

            group = self.getLayerGroup(groupIndex)
            if not group:
                QgsMessageLog.logMessage("Group not found", level=Qgis_Warning)
                self._clear_filter_value_loading()
                return

            current_field = self.dockwidget.filterAttributeComboBox.currentText()
            if not current_field or current_field == "Loading...":
                QgsMessageLog.logMessage(f"Invalid current field: {current_field}", level=Qgis_Warning)
                self._clear_filter_value_loading()
                return

            QgsMessageLog.logMessage(f"Selected field: {current_field}", level=Qgis_Info)

            layer = self._current_reference_vector_layer()
            if not layer:
                QgsMessageLog.logMessage(
                    "선택된 벡터 레이어가 없어 고유값을 가져올 수 없습니다.", level=Qgis_Warning
                )
                self._clear_filter_value_loading()
                return

            cache_key = self._filter_value_cache_key(groupIndex, layer, current_field)

            if cache_key in self.filter_value_cache and not manual:
                QgsMessageLog.logMessage("Using cached values", level=Qgis_Info)
                pairs = self._cached_entries_to_pairs(self.filter_value_cache[cache_key])
                self._populate_filter_value_combo_entries(pairs)
                return

            self.dockwidget.filterValueComboBox.clear()
            self.dockwidget.filterValueComboBox.addItem("Loading...")

            QgsMessageLog.logMessage(f"Processing layer: {layer.name()}", level=Qgis_Info)
            dp = layer.dataProvider()
            if not _provider_can_scan_unique_values(dp):
                QgsMessageLog.logMessage("Layer provider not available for unique values", level=Qgis_Warning)
                self._clear_filter_value_loading()
                return

            fieldIndex = layer.fields().indexOf(current_field)
            if fieldIndex < 0:
                QgsMessageLog.logMessage(f"Field index not found for: {current_field}", level=Qgis_Warning)
                self._clear_filter_value_loading()
                return

            QgsMessageLog.logMessage(f"Getting unique values for field index: {fieldIndex}", level=Qgis_Info)

            lbl = self._current_value_label_field_name()
            try:
                entries = self._build_filter_value_entries(
                    layer, dp, current_field, fieldIndex, lbl
                )
            except Exception as uv_err:
                QgsMessageLog.logMessage(
                    f"고유값/라벨 수집 실패: {uv_err}", level=Qgis_Critical
                )
                raise

            if entries:
                self._populate_filter_value_combo_entries(entries)
                self.filter_value_cache[cache_key] = list(entries)
                QgsMessageLog.logMessage(f"Found {len(entries)} value entries", level=Qgis_Info)
            else:
                QgsMessageLog.logMessage("No unique values found (모두 NULL이거나 비어 있음)", level=Qgis_Info)
                self._clear_filter_value_loading()

        except Exception as e:
            QgsMessageLog.logMessage(f"Error in updateDistinctValues: {str(e)}", level=Qgis_Critical)
            self._clear_filter_value_loading()

    def _updateFilterValuesUI(self, values, layer_id):
        """GUI 스레드에서 실행되는 필터 값 업데이트 메서드"""
        try:
            QgsMessageLog.logMessage(f"Updating UI with {len(values)} values", level=Qgis_Info)
            
            # 현재 선택된 그룹과 필드 확인
            groupIndex = self.dockwidget.layerGroupComboBox.currentIndex()
            if groupIndex < 0:
                return
                
            group = self.getLayerGroup(groupIndex)
            if not group:
                return
                
            current_field = self.dockwidget.filterAttributeComboBox.currentText()
            if not current_field:
                return
                
            layer = self._current_reference_vector_layer()
            if not layer:
                return
            cache_key = self._filter_value_cache_key(groupIndex, layer, current_field)
            pairs = [(str(v), str(v)) for v in sorted(str(x) for x in values)]
            self._populate_filter_value_combo_entries(pairs)
            self.filter_value_cache[cache_key] = list(pairs)
            QgsMessageLog.logMessage(f"Updated cache for key: {cache_key}", level=Qgis_Info)
            
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in _updateFilterValuesUI: {str(e)}", level=Qgis_Critical)

    def getFilterFieldIndex(self, layer):
        """최적화된 필터 필드 인덱스 조회"""
        try:
            layer_id = layer.id()
            field_name = self.dockwidget.filterAttributeComboBox.currentText()
            if not field_name:
                return -1
            cache_key = (layer_id, field_name)
            if cache_key in self.field_index_cache:
                return self.field_index_cache[cache_key]
            fieldIndex = layer.fields().indexOf(field_name)
            self.field_index_cache[cache_key] = fieldIndex
            return fieldIndex
        except Exception as e:
            QgsMessageLog.logMessage(f"Error getting filter field index: {str(e)}", tag="Smart Layer Filter")
            return -1

    def createSubsetString(self, layer, fieldIndex, values, presetIndex):
        """필터 문자열 생성"""
        if presetIndex is None:
            presetIndex = -1
            
        if not values: #set default value from GUI as list with single value
            values = []
            current_value = self._current_filter_value_code()
            if current_value and current_value != "Loading...":
                values.append(current_value)
            else:
                return ""  # 유효한 값이 없는 경우 빈 문자열 반환
            
        # presetIndex 유효성 검사
        if presetIndex < 0 or presetIndex >= len(self.filterPresets):
            return ""  # 유효하지 않은 인덱스인 경우 빈 문자열 반환
        
        #look up presetXml (XML object) 
        presetXml = self.filterPresets[presetIndex][1]
        
        #save filter operator
        filterOper = presetXml.find('operator').text
        
        #save filterColums as list of attibure name strings
        filterColumns = [col.text for col in presetXml.findall('column')]     
            
        #check if preset has ValueRelation, if so replace the value with a list of corresponing key's   
        vr = self.GetValueRelation(presetXml)
        if vr is not None:  # 명시적으로 None 체크
            values = self.getValueRelation(values[0], vr, invert=True, getAll=True)
            if not values:  # ValueRelation 결과가 None인 경우
                return ""  # 빈 문자열 반환
            
        # 필터 문자열 생성
        subsetString = ""
        for filterColumn in filterColumns:
            if filterColumn in layer.fields().names():
                firstValue = True
                for value in values:
                    if value is not None:  # None 값 제외
                        #if muliple values create 'OR' relations
                        if firstValue:                       
                            addSubSetstring = "\"{0}\" {1} '{2}'".format(filterColumn, filterOper, value)
                            firstValue = False
                        else:
                            addSubSetstring = addSubSetstring + " or " + "\"{0}\" {1} '{2}'".format(filterColumn, filterOper, value)
                
                #append the new SubSetstring with 'AND'relation to the current SubSetstring
                if subsetString == "":
                    subsetString = addSubSetstring
                else:
                    subsetString = subsetString + " and " + addSubSetstring
                    
        return subsetString

    def replaceFilters(self):
        """기존 필터를 새로운 필터로 교체"""
        try:
            current_field = self.dockwidget.filterAttributeComboBox.currentText()
            current_operator = self._current_filter_operator_symbol()
            current_value = self._current_filter_value_code()
            
            if current_field and current_value and current_value != "Loading...":
                # 필터 문자열 생성
                if current_operator in ['LIKE', 'ILIKE']:
                    filter_text = f'"{current_field}" {current_operator} \'%{current_value}%\''
                else:
                    filter_text = f'"{current_field}" {current_operator} \'{current_value}\''
                    
                QgsMessageLog.logMessage(f"Replacing filters with: {filter_text}", level=Qgis_Info)

                layer_ids = []
                for vl, lid in self._iter_filter_target_vector_layers():
                    vl.setSubsetString(filter_text)
                    layer_ids.append(lid)
                if layer_ids:
                    self.iface.mapCanvas().refresh()
                    for lid in layer_ids:
                        self.iface.layerTreeView().refreshLayerSymbology(lid)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in replaceFilters: {str(e)}", level=Qgis_Critical)

    def addFilter(self):
        """기존 필터에 새로운 필터 추가"""
        try:
            current_field = self.dockwidget.filterAttributeComboBox.currentText()
            current_operator = self._current_filter_operator_symbol()
            current_value = self._current_filter_value_code()
            
            if current_field and current_value and current_value != "Loading...":
                # 새로운 필터 문자열 생성
                if current_operator in ['LIKE', 'ILIKE']:
                    new_filter = f'"{current_field}" {current_operator} \'%{current_value}%\''
                else:
                    new_filter = f'"{current_field}" {current_operator} \'{current_value}\''
                    
                QgsMessageLog.logMessage(f"Adding filter: {new_filter}", level=Qgis_Info)

                layer_ids = []
                for vl, lid in self._iter_filter_target_vector_layers():
                    current_filter = vl.subsetString()
                    if current_filter:
                        vl.setSubsetString(f"({current_filter}) AND ({new_filter})")
                    else:
                        vl.setSubsetString(new_filter)
                    layer_ids.append(lid)
                if layer_ids:
                    self.iface.mapCanvas().refresh()
                    for lid in layer_ids:
                        self.iface.layerTreeView().refreshLayerSymbology(lid)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in addFilter: {str(e)}", level=Qgis_Critical)

    def clearFilters(self):
        """모든 필터 제거"""
        try:
            QgsMessageLog.logMessage("Clearing all filters", tag="Smart Layer Filter")

            layer_ids = []
            for vl, lid in self._iter_filter_target_vector_layers():
                vl.setSubsetString("")
                layer_ids.append(lid)
            if layer_ids:
                self.iface.mapCanvas().refresh()
                for lid in layer_ids:
                    self.iface.layerTreeView().refreshLayerSymbology(lid)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in clearFilters: {str(e)}", tag="Smart Layer Filter")

    def _group_state_key(self, group_index):
        if group_index is None or group_index < 0 or group_index >= len(self.allGroups):
            return None
        return self.allGroups[group_index][0]

    def _save_group_ui_state(self, group_index):
        key = self._group_state_key(group_index)
        if not key:
            return
        self.group_ui_state[key] = {
            'attribute': self.dockwidget.filterAttributeComboBox.currentText(),
            'operator': self._current_filter_operator_symbol(),
            'value': self._current_filter_value_code(),
            'value_label': self._current_value_label_field_name(),
            'sub_layer_id': self.dockwidget.layerInGroupComboBox.currentData(),
            'apply_group_filter': self.dockwidget.applyGroupFilterCheckBox.isChecked(),
        }

    def layerGroupChanged(self, index):
        """레이어 그룹이 변경될 때 호출되는 메서드"""
        QgsMessageLog.logMessage(f"layerGroupChanged called with index: {index}", tag="Smart Layer Filter")
        prev = self._active_layer_group_index
        if prev is not None and prev >= 0 and prev != index:
            self._save_group_ui_state(prev)

        self._active_layer_group_index = index if index >= 0 else None

        if index < 0:
            return
        try:
            group = self.getLayerGroup(index)
            if not group:
                return

            state = self.group_ui_state.get(self._group_state_key(index))

            self.dockwidget.applyGroupFilterCheckBox.blockSignals(True)
            self.dockwidget.applyGroupFilterCheckBox.setChecked(
                state.get('apply_group_filter', True) if state else True
            )
            self.dockwidget.applyGroupFilterCheckBox.blockSignals(False)

            preferred_id = state.get('sub_layer_id') if state else None
            layer = self._populate_layer_in_group_combo(group, preferred_id)
            if not layer:
                QgsMessageLog.logMessage(
                    "그룹에 벡터 레이어가 없어 필드 목록을 채울 수 없습니다.", tag="Smart Layer Filter"
                )
                self.dockwidget.filterAttributeComboBox.clear()
                self.dockwidget.valueLabelColumnComboBox.blockSignals(True)
                self.dockwidget.valueLabelColumnComboBox.clear()
                self.dockwidget.valueLabelColumnComboBox.blockSignals(False)
                self.dockwidget.filterValueComboBox.clear()
                return

            QgsMessageLog.logMessage(f"Reference layer: {layer.name()}", tag="Smart Layer Filter")

            fields = _field_names_for_filter_ui(layer)
            QgsMessageLog.logMessage(f"Available fields: {fields}", tag="Smart Layer Filter")

            self.dockwidget.filterAttributeComboBox.blockSignals(True)
            self.dockwidget.filterOperatorComboBox.blockSignals(True)

            self.dockwidget.filterAttributeComboBox.clear()
            self.dockwidget.filterAttributeComboBox.addItems(fields)

            if state:
                self._set_filter_operator_by_symbol(state.get('operator', '='))
                att = state.get('attribute', '')
                ai = self.dockwidget.filterAttributeComboBox.findText(att)
                if ai >= 0:
                    self.dockwidget.filterAttributeComboBox.setCurrentIndex(ai)
                elif fields:
                    self.dockwidget.filterAttributeComboBox.setCurrentIndex(0)
            elif fields:
                self.dockwidget.filterAttributeComboBox.setCurrentIndex(0)
                self._set_filter_operator_by_symbol('=')

            self._populate_value_label_column_combo(
                layer, state.get("value_label", "") if state else ""
            )

            self.dockwidget.filterOperatorComboBox.blockSignals(False)
            self.dockwidget.filterAttributeComboBox.blockSignals(False)

            saved_value = state.get('value', '') if state else ''

            if not self.dockwidget.filterAttributeComboBox.count():
                self.dockwidget.filterValueComboBox.clear()
                return

            if saved_value and saved_value != 'Loading...':
                self.updateDistinctValues()
                self._select_filter_value_by_code(saved_value)
            else:
                self.onFilterAttributeChanged(self.dockwidget.filterAttributeComboBox.currentIndex())
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in layerGroupChanged: {str(e)}", tag="Smart Layer Filter")

    def onLayerInGroupChanged(self, index):
        """같은 그룹에서 기준 레이어를 바꿀 때 필드·고유값 갱신."""
        if index < 0:
            return
        try:
            layer = self._current_reference_vector_layer()
            if not layer:
                self.dockwidget.filterAttributeComboBox.clear()
                self.dockwidget.valueLabelColumnComboBox.blockSignals(True)
                self.dockwidget.valueLabelColumnComboBox.clear()
                self.dockwidget.valueLabelColumnComboBox.blockSignals(False)
                self.dockwidget.filterValueComboBox.clear()
                return
            prev_field = self.dockwidget.filterAttributeComboBox.currentText()
            prev_lbl = self._current_value_label_field_name()
            fields = _field_names_for_filter_ui(layer)
            self.dockwidget.filterAttributeComboBox.blockSignals(True)
            self.dockwidget.filterAttributeComboBox.clear()
            self.dockwidget.filterAttributeComboBox.addItems(fields)
            fi = self.dockwidget.filterAttributeComboBox.findText(prev_field)
            if prev_field and fi >= 0:
                self.dockwidget.filterAttributeComboBox.setCurrentIndex(fi)
            elif fields:
                self.dockwidget.filterAttributeComboBox.setCurrentIndex(0)
            self.dockwidget.filterAttributeComboBox.blockSignals(False)
            self._populate_value_label_column_combo(layer, prev_lbl)
            self.onFilterAttributeChanged(self.dockwidget.filterAttributeComboBox.currentIndex())
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in onLayerInGroupChanged: {str(e)}", tag="Smart Layer Filter")
                
    def onFilterAttributeChanged(self, index):
        """필터 속성이 변경될 때 호출되는 메서드"""
        QgsMessageLog.logMessage(f"onFilterAttributeChanged called with index: {index}", level=Qgis_Info)
        if index >= 0:  # 유효한 인덱스인 경우에만 처리
            try:
                current_field = self.dockwidget.filterAttributeComboBox.currentText()
                QgsMessageLog.logMessage(f"Selected field: {current_field}", level=Qgis_Info)
                layer = self._current_reference_vector_layer()
                if layer:
                    self._populate_value_label_column_combo(
                        layer, self._current_value_label_field_name()
                    )
                # 필터 값 콤보박스 초기화
                self.dockwidget.filterValueComboBox.clear()
                self.dockwidget.filterValueComboBox.addItem("Loading...")
                
                # 필터 값 업데이트
                self.updateDistinctValues()
            except Exception as e:
                QgsMessageLog.logMessage(f"Error in onFilterAttributeChanged: {str(e)}", level=Qgis_Critical)

    def getLayerGroup(self, index):
        """레이어 그룹을 가져오는 메서드"""
        if index < 0 or index >= len(self.allGroups):
            return None
        entry = self.allGroups[index]
        if len(entry) >= 3 and entry[2] is not None:
            return entry[2]
        return self.root.findGroup(entry[0])
            
    def updateGUI(self, index):
        """필터 값이 변경될 때 호출되는 메서드"""
        if index >= 0:  # 유효한 인덱스인 경우에만 처리
            try:
                current_field = self.dockwidget.filterAttributeComboBox.currentText()
                current_value = self._current_filter_value_code()
                
                if current_field and current_value and current_value != "Loading...":
                    # 필터 문자열 생성
                    filter_text = f'"{current_field}" = \'{current_value}\''
                    QgsMessageLog.logMessage(f"Generated filter text: {filter_text}", tag="Smart Layer Filter")
                    
                    layer_ids = []
                    for vl, lid in self._iter_filter_target_vector_layers():
                        vl.setSubsetString(filter_text)
                        layer_ids.append(lid)
                    if layer_ids:
                        self.iface.mapCanvas().refresh()
                        for lid in layer_ids:
                            self.iface.layerTreeView().refreshLayerSymbology(lid)
            except Exception as e:
                QgsMessageLog.logMessage(f"Error in updateGUI: {str(e)}", tag="Smart Layer Filter")

    def loadXml(self):
        fileName, _ = QFileDialog.getOpenFileName(
            self.dockwidget, "Select XML filter Preset XML ", "", "Filter preset (*.xml)"
        )
        if not fileName:
            return
        with open(fileName, "r", encoding="utf-8", errors="replace") as xml_file:
            presetXml = xml_file.read().strip()
        QgsExpressionContextUtils.setProjectVariable(QgsProject.instance(), "groupFilterPresets", presetXml)
        self.reloadProject()